### ISSUE TITLE
Text alignment issue in Header

### ISSUE THREAD

**Issue by bogy0** [IBM/video-streaming-developer-docs#7]
the text in the Header: "IBM **Video Streaming** Developers" seems a bit misaligned, it seems a baseline issue, please fix.

**Comment by mariuszmickiewicz** [comment]
This happens in Firefox. 
If this issue is coming from Gatsby, this should be addressed at the source.

![image](https://user-images.githubusercontent.com/12408951/88814488-76793a80-d1ba-11ea-8a20-6dc16c8b9450.png)
